import images from "./src/assets/images";

export const activities = [
  {
    name: "Trekking",
  },
  {
    name: "Rafting",
  },
  {
    name: "Paragliding",
  },
  {
    name: "Mountain Climbing",
  },
  {
    name: "Safari",
  },
];

export const searchData = ["trek", "raffle", "paraglide"];

export const stories = [
  {
    id: 1,
    title: "Exploring the Cultural Treasures of Kathmandu Valley",
    location: "Kathmandu",
    description:
      "The Kathmandu Valley is a cultural hub and home to several UNESCO World Heritage Sites, including Kathmandu Durbar Square, Patan Durbar Square, and Bhaktapur Durbar Square. Visitors can explore ancient temples, palaces, and bustling marketplaces, immersing themselves in the rich history and architecture of the region.",
    image: images.kathmandu,
    date: "2023-08-15",
  },
  {
    id: 2,
    title:
      "Journey to the Roof of the World: Trekking to Mount Everest Base Camp",
    location: "Solukhumbu District",
    description:
      "Mount Everest, the highest peak in the world, attracts adventurers and climbers from around the globe. While summiting Everest is a challenging feat reserved for experienced mountaineers, trekking to Everest Base Camp offers a memorable journey through the stunning Himalayan landscape.",
    image: images.everest,
    date: "2023-09-20",
  },
  {
    id: 3,
    title: "Discovering Paradise: Exploring Pokhara's Natural Wonders",
    location: "Gandaki Province",
    description:
      "Pokhara is known for its breathtaking natural beauty, with stunning views of the Annapurna and Dhaulagiri mountain ranges reflected in the serene waters of Phewa Lake. Visitors can enjoy boating on the lake, exploring caves, and hiking to nearby viewpoints for panoramic vistas.",
    image: images.pokhara,
    date: "2023-10-10",
  },
  {
    id: 4,
    title:
      "Wildlife Safari in Chitwan National Park: A Journey into the Heart of Nature",
    location: "Chitwan District",
    description:
      "Chitwan National Park is a haven for wildlife enthusiasts, home to a diverse range of flora and fauna, including endangered species such as the Bengal tiger and one-horned rhinoceros. Visitors can enjoy jungle safaris, birdwatching, and cultural experiences with the indigenous Tharu community.",
    image: images.chitwan,
    date: "2023-11-05",
  },
];

export const Trip = [
  {
    tripId: 1,
    tripName: "Buddhist Tour In Nepal",
    image: images.chitwan,
    days: 8,
    tripDetails: {
      accomodation: "Hotel/Lodge",
      arrivalCity: "Kathmandu",
      bestSeason: "Spring and Autumn",
      guide: "Guided Tour",
      maximumAltitude: "2,195 meters (7,201 feet)",
      meals: "BLD",
      transportation: "Private/Public Vehicle",
      wifi: "Available",
    },
    overview: [
      "Nepal being the birthplace of Gautam Buddha, is very revered among Buddhists. It houses a myriad number of Buddhist pilgrimage sites. If you are to visit Nepal, you cannot miss visiting these significant sites. They are scattered around various geographical regions of Nepal. We at Great Adventure Treks have several packages aimed at Buddhist pilgrimage tours. On this package of Buddhist tour in Nepal, we propose a tour in and around Kathmandu valley along with a tour to Lumbini. It will be an 8-day long trip around major Buddhist attraction sites.",
      "We will kick off our tour from Kathmandu by visiting the attraction sites within the valley. After that, we then head towards Pharping and its vicinity to visit its pilgrimages. We also have places like Patan, Bhaktapur, and the famous Manjushree Park as our destinations. On one of the days of the tour, our overnight stop will be Nagarkot. We will visit Namobuddha and Panauti on the outskirts of town. They are a must-visit site among significant Buddhist attraction sites. After that, we will head to the birthplace of Buddha, Lumbini. A short tour of pilgrimage sites in Lumbini, and then we return to Kathmandu and mark the end of the trip.",
      "The trip will be brief and very suitable for a short family gateway. You need not put much physical effort or plan your itineraries as we do it for you. Just book your package and enjoy the cultural and religious adventure that this tour has in store for you",
    ],
    itinerary: [
      "Visit Swayambhunath, Kathmandu Durbar Square, and nearby Buddhist viharas",
      "Baudhanath & Bajrayogini (Sankhu)",
      "Pharping, Yangleshor, Asura cave, Bajrayogini",
      "Bhaktapur or Patan, Manjushree cave Overnight Nagarkot",
      "Namobuddha, Panauti",
      "Kathmandu to Lumbini",
      "Lumbini / Kapilvastu / Taulihawa / Ram Gram",
      "Lumbini to Kathmandu",
    ],
    costExcluded: [
      "International flight ticket and airport taxes are not included in the package.",
      "Nepal visa fees are not included in the package.",
      "Gratuities for guides and drivers are not included in the package.",
      "Any expenses of a personal nature are not included in the package.",
      "Travel/medical insurance and the cost of emergency evacuation are not included in the package.",
    ],
  },
  {
    tripId: 2,
    tripName: "Everest Base Camp Helicopter tour",
    image: images.helicopter,
    days: 1,
    tripDetails: {
      accomodation: "Hotel/Lodge",
      arrivalCity: "Kathmandu",
      bestSeason: "Spring and Autumn",
      guide: "Guided Tour",
      maximumAltitude: "2,195 meters (7,201 feet)",
      meals: "BLD",
      transportation: "Private/Public Vehicle",
      wifi: "Available",
    },
    overview: [
      "Everest Base Camp Helicopter tour is the easiest way to confront the highest peak of the world, Mt. Everest (8848m). This short trip will also take you to the topmost base camp in the world i.e. Everest Base Camp itself along with famous vantage points like Kala Patthar (5565m).",
      "Treks like Everest Base Camp will take a minimum of 13 days for exploration. Plus the trek is strenuous and you have to look after various factors like acclimatization. Thus, the EBC Helicopter Tour is the right option for avoiding these hurdles. You will reach the destined point in no time without going through any physical and climatic extremities.",
      "You can spot about 20 highest peaks of East Nepal. You can locate the peaks (>8000m) like Everest (8848m), Cho Oyu (8201m), Shisha Pangma (8013m), Pumori (8171m), and Lhotse (8516m). These soaring peaks, with only 20 miles from your window, look magical. Above the horizon, you will forget about all kinds of crowd & chaos. All you do is delve deep into the serenity of beautiful Himalayas.",
    ],
    itinerary: [
      "Visit Swayambhunath, Kathmandu Durbar Square, and nearby Buddhist viharas",
      "Baudhanath & Bajrayogini (Sankhu)",
      "Pharping, Yangleshor, Asura cave, Bajrayogini",
      "Bhaktapur or Patan, Manjushree cave Overnight Nagarkot",
      "Namobuddha, Panauti",
      "Kathmandu to Lumbini",
      "Lumbini / Kapilvastu / Taulihawa / Ram Gram",
      "Lumbini to Kathmandu",
    ],
    costExcluded: [
      "International flight ticket and airport taxes are not included in the package.",
      "Nepal visa fees are not included in the package.",
      "Gratuities for guides and drivers are not included in the package.",
      "Any expenses of a personal nature are not included in the package.",
      "Travel/medical insurance and the cost of emergency evacuation are not included in the package.",
    ],
  },
  {
    tripId: 3,
    tripName: "Kathmandu and Pokhara Tour",
    image: images.pokhara,
    days: 8,
    tripDetails: {
      accomodation: "Hotel/Lodge",
      arrivalCity: "Kathmandu",
      bestSeason: "Spring and Autumn",
      guide: "Guided Tour",
      maximumAltitude: "2,195 meters (7,201 feet)",
      meals: "BLD",
      transportation: "Private/Public Vehicle",
      wifi: "Available",
    },
    overview: [
      "Nepal being the birthplace of Gautam Buddha, is very revered among Buddhists. It houses a myriad number of Buddhist pilgrimage sites. If you are to visit Nepal, you cannot miss visiting these significant sites. They are scattered around various geographical regions of Nepal. We at Great Adventure Treks have several packages aimed at Buddhist pilgrimage tours. On this package of Buddhist tour in Nepal, we propose a tour in and around Kathmandu valley along with a tour to Lumbini. It will be an 8-day long trip around major Buddhist attraction sites.",
      "We will kick off our tour from Kathmandu by visiting the attraction sites within the valley. After that, we then head towards Pharping and its vicinity to visit its pilgrimages. We also have places like Patan, Bhaktapur, and the famous Manjushree Park as our destinations. On one of the days of the tour, our overnight stop will be Nagarkot. We will visit Namobuddha and Panauti on the outskirts of town. They are a must-visit site among significant Buddhist attraction sites. After that, we will head to the birthplace of Buddha, Lumbini. A short tour of pilgrimage sites in Lumbini, and then we return to Kathmandu and mark the end of the trip.",
      "The trip will be brief and very suitable for a short family gateway. You need not put much physical effort or plan your itineraries as we do it for you. Just book your package and enjoy the cultural and religious adventure that this tour has in store for you",
    ],
    itinerary: [
      "Visit Swayambhunath, Kathmandu Durbar Square, and nearby Buddhist viharas",
      "Baudhanath & Bajrayogini (Sankhu)",
      "Pharping, Yangleshor, Asura cave, Bajrayogini",
      "Bhaktapur or Patan, Manjushree cave Overnight Nagarkot",
      "Namobuddha, Panauti",
      "Kathmandu to Lumbini",
      "Lumbini / Kapilvastu / Taulihawa / Ram Gram",
      "Lumbini to Kathmandu",
    ],
    costExcluded: [
      "International flight ticket and airport taxes are not included in the package.",
      "Nepal visa fees are not included in the package.",
      "Gratuities for guides and drivers are not included in the package.",
      "Any expenses of a personal nature are not included in the package.",
      "Travel/medical insurance and the cost of emergency evacuation are not included in the package.",
    ],
  },
  {
    tripId: 4,
    tripName: "Everest Base Camp Trek",
    image: images.everest,
    days: 8,
    tripDetails: {
      accomodation: "Hotel/Lodge",
      arrivalCity: "Kathmandu",
      bestSeason: "Spring and Autumn",
      guide: "Guided Tour",
      maximumAltitude: "2,195 meters (7,201 feet)",
      meals: "BLD",
      transportation: "Private/Public Vehicle",
      wifi: "Available",
    },
    overview: [
      "Nepal being the birthplace of Gautam Buddha, is very revered among Buddhists. It houses a myriad number of Buddhist pilgrimage sites. If you are to visit Nepal, you cannot miss visiting these significant sites. They are scattered around various geographical regions of Nepal. We at Great Adventure Treks have several packages aimed at Buddhist pilgrimage tours. On this package of Buddhist tour in Nepal, we propose a tour in and around Kathmandu valley along with a tour to Lumbini. It will be an 8-day long trip around major Buddhist attraction sites.",
      "We will kick off our tour from Kathmandu by visiting the attraction sites within the valley. After that, we then head towards Pharping and its vicinity to visit its pilgrimages. We also have places like Patan, Bhaktapur, and the famous Manjushree Park as our destinations. On one of the days of the tour, our overnight stop will be Nagarkot. We will visit Namobuddha and Panauti on the outskirts of town. They are a must-visit site among significant Buddhist attraction sites. After that, we will head to the birthplace of Buddha, Lumbini. A short tour of pilgrimage sites in Lumbini, and then we return to Kathmandu and mark the end of the trip.",
      "The trip will be brief and very suitable for a short family gateway. You need not put much physical effort or plan your itineraries as we do it for you. Just book your package and enjoy the cultural and religious adventure that this tour has in store for you",
    ],
    itinerary: [
      "Visit Swayambhunath, Kathmandu Durbar Square, and nearby Buddhist viharas",
      "Baudhanath & Bajrayogini (Sankhu)",
      "Pharping, Yangleshor, Asura cave, Bajrayogini",
      "Bhaktapur or Patan, Manjushree cave Overnight Nagarkot",
      "Namobuddha, Panauti",
      "Kathmandu to Lumbini",
      "Lumbini / Kapilvastu / Taulihawa / Ram Gram",
      "Lumbini to Kathmandu",
    ],
    costExcluded: [
      "International flight ticket and airport taxes are not included in the package.",
      "Nepal visa fees are not included in the package.",
      "Gratuities for guides and drivers are not included in the package.",
      "Any expenses of a personal nature are not included in the package.",
      "Travel/medical insurance and the cost of emergency evacuation are not included in the package.",
    ],
  },
  {
    tripId: 5,
    tripName: "Lobuche East Peak Climbing",
    image: images.labuche,
    days: 8,
    tripDetails: {
      accomodation: "Hotel/Lodge",
      arrivalCity: "Kathmandu",
      bestSeason: "Spring and Autumn",
      guide: "Guided Tour",
      maximumAltitude: "2,195 meters (7,201 feet)",
      meals: "BLD",
      transportation: "Private/Public Vehicle",
      wifi: "Available",
    },
    overview: [
      "Nepal being the birthplace of Gautam Buddha, is very revered among Buddhists. It houses a myriad number of Buddhist pilgrimage sites. If you are to visit Nepal, you cannot miss visiting these significant sites. They are scattered around various geographical regions of Nepal. We at Great Adventure Treks have several packages aimed at Buddhist pilgrimage tours. On this package of Buddhist tour in Nepal, we propose a tour in and around Kathmandu valley along with a tour to Lumbini. It will be an 8-day long trip around major Buddhist attraction sites.",
      "We will kick off our tour from Kathmandu by visiting the attraction sites within the valley. After that, we then head towards Pharping and its vicinity to visit its pilgrimages. We also have places like Patan, Bhaktapur, and the famous Manjushree Park as our destinations. On one of the days of the tour, our overnight stop will be Nagarkot. We will visit Namobuddha and Panauti on the outskirts of town. They are a must-visit site among significant Buddhist attraction sites. After that, we will head to the birthplace of Buddha, Lumbini. A short tour of pilgrimage sites in Lumbini, and then we return to Kathmandu and mark the end of the trip.",
      "The trip will be brief and very suitable for a short family gateway. You need not put much physical effort or plan your itineraries as we do it for you. Just book your package and enjoy the cultural and religious adventure that this tour has in store for you",
    ],
    itinerary: [
      "Visit Swayambhunath, Kathmandu Durbar Square, and nearby Buddhist viharas",
      "Baudhanath & Bajrayogini (Sankhu)",
      "Pharping, Yangleshor, Asura cave, Bajrayogini",
      "Bhaktapur or Patan, Manjushree cave Overnight Nagarkot",
      "Namobuddha, Panauti",
      "Kathmandu to Lumbini",
      "Lumbini / Kapilvastu / Taulihawa / Ram Gram",
      "Lumbini to Kathmandu",
    ],
    costExcluded: [
      "International flight ticket and airport taxes are not included in the package.",
      "Nepal visa fees are not included in the package.",
      "Gratuities for guides and drivers are not included in the package.",
      "Any expenses of a personal nature are not included in the package.",
      "Travel/medical insurance and the cost of emergency evacuation are not included in the package.",
    ],
  },
  {
    tripId: 6,
    tripName: "Kanchenjunga Trek",
    image: images.treking,
    days: 8,
    tripDetails: {
      accomodation: "Hotel/Lodge",
      arrivalCity: "Kathmandu",
      bestSeason: "Spring and Autumn",
      guide: "Guided Tour",
      maximumAltitude: "2,195 meters (7,201 feet)",
      meals: "BLD",
      transportation: "Private/Public Vehicle",
      wifi: "Available",
    },
    overview: [
      "Kanchenjunga Trekking is one of the most gorgeous trekking trails in Nepal. The trek takes you to one of the peak massifs in the world, Mt. Kanchenjunga. Kanchenjunga means ‘Five Treasures of the Great Snow’ in the Tibetan language. They denote the five summits that makeup Kanchenjunga range. Kanchenjunga Trekking is an unspoiled trekking trail in eastern Nepal. It is a restricted trekking territory. You must trek with a local guide and at least 2 trekkers. This is the most followed rule set by the Government of Nepal.",
      "The trail to the Kanchenjunga Base Camp trek is less crowded. The trek plunders the trekkers with a unique insight into the remote part of Eastern Nepal. Also, you can observe the rural lifestyles in the region. Trekking in Kanchenjunga tenders the most beautiful Himalayan scenery. You will perceive the best outlook of Mt. Kanchenjunga, Mt. Makalu, and Jahnu Himal. You will also see gigantic heights of Mt. Rohtang and Kabru above a moraine on the Nepal-Sikkim border. During the trail, you will see the regular changes in the landscape. The trek offers diversified flora and wildlife. On the trek, we will pass through the cosseted areas of the Kanchenjunga Conservation Area. We can observe numerous wildlife and birds like pheasant, dragon, snow leopard, black bear, red panda, etc.",
    ],
    itinerary: [
      "Arrive in Kathmandu",
      "Permit Preparation and half day sightseeing",
      "Flight to Bhadrapur (40 – 45 min) and drive Phidim (4 hrs), Tea House Accommodation.",
      "Drive to Taplejung (1,820m/5970ft) 8hrs, Tea House Accommodation.",
      "rek to Chirwa (1,270m/4166ft) 6 -7 hrs, Tea House Accommodation.",
      "Trek to Amjlosa (2,520m/8266ft) 8-9 hrs, Tea House Accommodation.",
      "Trek to Gyabla (2,730m/8955ft) 4 -5 hrs, Tea House Accommodation.",
      "Trek to Ghunsa (3,595m/11791ft) 5 hrs, Tea House Accommodation.",
      "Acclimatization Day at Ghunsa.",
      "Trek to Kambachen (4,050m/13286ft) 5 – 6 hrs, Tea House Accommodation.",
      "Trek to Lhonak (4,780m/15780ft) 7 hrs, Tea House Accommodation.",
      "Trek to Pangpema (5,065m/16615ft) 6 hrs, Tea House Accommodation.",
    ],
    costExcluded: [
      "Lunch and dinner in Kathmandu.",
      "Any kinds of Drinks (soft and Hard Drinks)",
      "Visa, international flight ticket",
      "Personal Nature expenses",
      "Tips for Staffs",
      "Trekking Equipment",
      "Rescue and Evacuation cost",
      "Kathmandu Monuments fees",
      "shower during the trek",
      "Bar bills",
      "If you use high level accommodation.",
    ],
  },
];
